export const initialCountries = [
  'USA',
  'Canada',
  'Mexico',
  'Germany',
  'France',
  'Japan',
  'Brazil',
  'India',
  'China',
  'Australia',
  'Russia',
  'United Kingdom',
  'Italy',
  'Spain',
  'South Korea',
  'Netherlands',
  'Turkey',
  'Switzerland',
  'Sweden',
  'Belgium',
  'Argentina',
  'South Africa',
  'New Zealand',
  'Norway',
  'Poland',
  'Denmark',
  'Ireland',
  'Portugal',
  'Greece',
  'Finland',
  'Austria',
  'Israel',
  'Czech Republic',
  'Hungary',
  'Chile',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Philippines',
  'Indonesia',
  'Vietnam',
  'Saudi Arabia',
  'United Arab Emirates',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Ethiopia',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Colombia',
  'Venezuela',
  'Peru',
  'Uruguay',
  'Paraguay',
  'Bolivia',
  'Ecuador',
  'Guatemala',
  'Panama',
  'Costa Rica',
  'El Salvador',
  'Honduras',
  'Nicaragua',
  'Cuba',
  'Dominican Republic',
  'Haiti',
  'Jamaica',
  'Trinidad and Tobago',
  'Barbados',
  'Bahamas',
  'Iceland',
  'Luxembourg',
  'Monaco',
  'Liechtenstein',
  'Malta',
  'Cyprus',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Slovakia',
  'Slovenia',
  'Croatia',
  'Bosnia and Herzegovina',
  'Montenegro',
  'Serbia',
  'Kosovo',
  'Macedonia',
  'Albania',
  'Georgia',
  'Armenia',
  'Azerbaijan',
  'Kazakhstan',
  'Uzbekistan',
  'Turkmenistan',
  'Kyrgyzstan',
  'Tajikistan',
  'Mongolia',
  'Myanmar',
  'Bangladesh',
  'Nepal',
  'Bhutan',
  'Sri Lanka',
];
